#!/sbin/openrc-run

# alpine startup for goproxy
# Sudhi Herle Aug 2019

name=$RC_SVCNAME
description="Socks v5 and HTTP proxy"
commane="/usr/bin/goproxy"
confdir="/etc/goproxy"
conf="$confdir/goproxy.conf"
command_background="true"
command_args="$conf"
command_user="nobody:nogroup"
pidfile="/run/$name.pid"

required_dirs="$confdir"
required_files="$command $conf"


depend() {
    need net logger dns
    #use logger dns
    after bootmisc
}
