#! /bin/sh

# Build linux debian package


# Bump this for every new release
VER=0.2.0


die() {
    echo "$0: $@" 1>&2
    exit 1
}

#set -x

mk=`which mk-deb.py`
if [ "x$mk" = "x" ]; then
    die "Can't find mk-deb.py"
fi

GOOS=linux
GOARCH=amd64
export GOOS GOARCH

pwd=`pwd`
for a in amd64 arm64; do
    ./build -s -a linux-$a -V $VER  || exit 1
    $mk $a $pwd/debian $VER $pwd    || exit 1
done
