#! /bin/sh

# Build linux debian package


# Bump this for every new release
VER=0.7.0

# Arch for which we want to build
ARCH="amd64"


die() {
    echo "$0: $@" 1>&2
    exit 1
}

#set -x

# My uber-simple debianizer for any program
mk=`which mk-deb.py`
if [ "x$mk" = "x" ]; then
    die "Can't find mk-deb.py"
fi


pwd=`pwd`
for a in $ARCH; do
    ./build -s -a linux-$a -V $VER  || exit 1
    $mk $a $pwd/debian $VER $pwd    || exit 1
done
